# Generated by Django 6.0.5 on 2026-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='6,7,8,9,10', max_length=100),
        ),
    ]
